# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - next*
      - main
      - release/*

env:
  NODE_VERSION: latest

jobs:
  build-ts:
    name: Build Typescript
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - folder: api
          - folder: crawler
          - folder: telegram-notifier
          - folder: pwa

    permissions:
      contents: read
      security-events: write

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v3

      - name: 🏗 Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: 🏗 Install dependencies
        working-directory: ${{ matrix.folder }}
        run: yarn install --frozen-lockfile

      - name: 🚀 Build Typescript
        working-directory: ${{ matrix.folder }}
        run: yarn build
